name: app
publish_to: 'none'
version: 0.0.10+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chewie: ^1.2.2
  firebase_database: ^8.0.0
  floor: ^1.2.0
  flutter_easyloading: ^3.0.3
  get: ^4.3.8
  permission_handler: ^8.1.6
  video_player: ^2.2.3
  firebase_core: ^1.6.0
  http: ^0.13.3
  lottie: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  floor_generator: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/